theme: jekyll-theme-minimal
title: SAP Business One
description: Repositorio libre con c√≥digos para aprender SAP Business One.
# google_analytics: UA-102273252-1
avatar: https://avatars2.githubusercontent.com/u/23317692?v=3&u=3319301a436f2b42d9c4fa89370ddc2e40c0feea
gems:
  - jekyll-sitemap
